version: '3.8'
services:
  frontend:
    container_name: acadia_frontend
    restart: always
    build: ./frontend
    ports: ["8080:8080"]
    depends_on:
      - backend

  backend:
    container_name: acadia_backend
    restart: always
    build: ./backend
    ports: ["5000:5000"]